[header]
    style = "header"
    [header.text_box]
        style = "header_text_box"
        [header.text_box.text]
            style = "header_text"
            text  = "{{title, 'Puree UI Kit'}}"
            font  = "NeueMontreal-Bold"
        [header.text_box.text1]
            style = "header_text1"
            text  = "{{subtitle, 'Declarative UI for Blender'}}"
            font  = "NeueMontreal-Italic"
    [header.logoh]
        style = "header_logoh"
        img   = "loggoui2"