schema_version = "1.0.0"

id         = "xwz_puree_ui"
version    = "0.0.7"
name       = "Puree UI"
tagline    = "XWZ Puree UI"
maintainer = "Nicolai Prodromov"
type       = "add-on"

blender_version_min = "4.2.0"

license = [
  "MIT",
]

platforms = [
  "windows-x64",
  "linux-x64",
  "macos-arm64",
  "macos-x64"
  ]

wheels = [
  "./wheels/puree_ui-0.0.7-py3-none-any.whl"
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.zip",
  "*.pyc",
  
  ".git/",
  ".vscode/",
  "dist/",
  "docs/",
  ".gitignore",
  ".blender_manifest.example.toml",
  "justfile",
  "Makefile",
  "MANIFEST.in",
  "Pipfile",
  "Pipfile.lock",
  "requirements.txt",
  "setup.py",
]