schema_version = "1.0.0"

id         = "xwz_puree_ui"
version    = "0.1.2"
name       = "Puree UI"
tagline    = "XWZ Puree UI"
maintainer = "Nicolai Prodromov"
type       = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Nicolai Prodromov",
]

platforms = [
  "windows-x64",
  "linux-x64",
  "macos-arm64",
  "macos-x64"
  ]

wheels = [
  "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
  "./wheels/attrs-25.3.0-py3-none-any.whl",
  "./wheels/glcontext-3.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/moderngl-5.12.0-cp311-cp311-win_amd64.whl",
  "./wheels/stretchable-1.1.7-cp38-abi3-win_amd64.whl",
  "./wheels/typing_extensions-4.15.0-py3-none-any.whl",
  "./wheels/puree_ui-0.1.2-py3-none-any.whl"
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.zip",
  "*.pyc",
  
  ".git/",
  ".vscode/",
  "dist/",
  "docs/",
  ".gitignore",
  ".blender_manifest.example.toml",
  "justfile",
  "Makefile",
  "MANIFEST.in",
  "Pipfile",
  "Pipfile.lock",
  "requirements.txt",
  "setup.py",
  "puree/puree_core/",
]