[app]
    selected_theme = "xwz_default"
    default_theme  = "xwz_default"
[[app.theme]]
    name         = "xwz_default"
    author       = "xwz"
    version      = "1.0.0"
    default_font = "NeueMontreal-Regular"
    scripts      = ["static/script.py"]
    styles       = ["static/style.css"]
    components   = "static/components/"
    [app.theme.root]
        style = "root"
        [app.theme.root.bg]
            style = "bg"
            [app.theme.root.bg.header1]
                data = "[header]"
            [app.theme.root.bg.body]
                style = "body"
                [app.theme.root.bg.body.buttons_test1]
                    style = "buttons_test1"
                    
                    [app.theme.root.bg.body.buttons_test1.hover_test]
                        data          = "[test_button]"
                        tb_text_style = "ht_text"
                        tb_style      = "hover_test"
                        tb_text       = "Hover me!"

                    [app.theme.root.bg.body.buttons_test1.click_test]
                        data          = "[test_button]"
                        tb_text_style = "ct_text"
                        tb_style      = "click_test"
                        tb_text       = "Click me!"

                    [app.theme.root.bg.body.buttons_test1.toggle_test]
                        data          = "[test_button]"
                        tb_text_style = "tg_text"
                        tb_style      = "toggle_test"
                        tb_text       = "Toggle me!"

                    
