[app]
    selected_theme = "xwz_default"
    default_theme  = "xwz_default"
[[app.theme]]
    name         = "xwz_default"
    author       = "xwz"
    version      = "1.0.0"
    default_font = "NeueMontreal-Regular"
    scripts      = ["static/script.py"]
    styles       = ["static/style.css"]
    components   = "static/components/"
    [app.theme.root]
        style = "root"
        [app.theme.root.bg]
            style = "bg"

            [app.theme.root.bg.top_box]
                style = "top_box"
                [app.theme.root.bg.top_box.left_box]
                    style = "left_box"
                    [app.theme.root.bg.top_box.left_box.left_top_box]
                        style = "left_top_box"


                        [app.theme.root.bg.top_box.left_box.left_top_box.left_top_box_box]
                            style = "left_top_box_box"
                            [app.theme.root.bg.top_box.left_box.left_top_box.left_top_box_box.ht]
                                data          = "[test_button]"
                                tb_text       = "Hover me!"
                                tb_style      = "hover_test"
                                tb_text_style = "ht_text"
                                tb_font       = "NeueMontreal-BoldItalic"

                        [app.theme.root.bg.top_box.left_box.left_top_box.middle_top_box]
                            style = "middle_top_box"
                            [app.theme.root.bg.top_box.left_box.left_top_box.middle_top_box.ct]
                                data          = "[test_button]"
                                tb_text       = "Click me!"
                                tb_style      = "click_test"
                                tb_text_style = "ct_text"
                                tb_font       = "NeueMontreal-BoldItalic"


                    [app.theme.root.bg.top_box.left_box.left_bottom_box]
                        style = "left_bottom_box"
                        [app.theme.root.bg.top_box.left_box.left_bottom_box.tgt]
                            data          = "[test_button]"
                            tb_text       = "Toggle me!"
                            tb_style      = "toggle_test"
                            tb_text_style = "tgt_text"
                            tb_font       = "NeueMontreal-BoldItalic"


                [app.theme.root.bg.top_box.right_box]
                    style = "right_box"
                    [app.theme.root.bg.top_box.right_box.right_top_box]
                        style = "right_top_box"
                        [app.theme.root.bg.top_box.right_box.right_top_box.img_test]
                            style = "img_test"
                            img   = "Asset2"

                    [app.theme.root.bg.top_box.right_box.right_bottom_box]
                        style = "right_bottom_box"

            [app.theme.root.bg.bottom_text_box]
                style = "bottom_text_box"
                [app.theme.root.bg.bottom_text_box.bottom_text_box_title]
                    style = "bottom_text_box_title"
                    text  = "PUREE UI KIT by xwz"
                    font  = "NeueMontreal-Bold"
