[app]
    selected_theme = "xwz_default"
    default_theme  = "xwz_default"
[app.settings]
    scroll_speed = 100
[[app.theme]]
    name    = "xwz_default"
    author  = "xwz"
    version = "1.0.0"
    scripts = ["script.py"]
    styles  = ["style.css"]
    [app.theme.root]
        style = "root"
        [app.theme.root.bg]
            style = "bg"
            [app.theme.root.bg.header]
                style = "header"
                [app.theme.root.bg.header.text]
                    style = "header_text"
                    text  = "Slippers UI KIT"
                [app.theme.root.bg.header.logoh]
                    style = "header_logoh"
                    img   = "loggoui2"
            [app.theme.root.bg.body]
                style = "body"
                [app.theme.root.bg.body.card1]
                    style = "card1"