title: Puree
description: Declarative UI Framework for Blender
author: Nicolai Prodromov

url: https://nicolaiprodromov.github.io
baseurl: /puree

remote_theme: cotes2020/jekyll-theme-chirpy

lang: en

timezone: America/New_York

theme_mode: dark

social:
  name: Nicolai Prodromov
  links:
    - https://github.com/nicolaiprodromov

github:
  username: nicolaiprodromov

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-seo-tag