title: Puree
description: Declarative UI Framework for Blender
author: Nicolai Prodromov

title: Puree
description: Declarative UI Framework for Blender
author: Nicolai Prodromov

url: https://nicolaiprodromov.github.io
baseurl: /puree

remote_theme: pages-themes/slate@v0.2.0

show_downloads: false

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate