lang: en

timezone: UTC

title: Puree
tagline: Declarative UI Framework for Blender
description: A declarative UI framework for Blender addons and much more

url: "https://nicolaiprodromov.github.io"
baseurl: "/puree"

github:
  username: nicolaiprodromov

social:
  name: Nicolai Prodromov
  email: ""
  links:
    - https://github.com/nicolaiprodromov

remote_theme: cotes2020/jekyll-theme-chirpy

theme_mode: dark

toc: true

comments:
  active: false

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - "*.config.js"
  - docs.aep
  - BA_POST.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock