title: Puree
description: Declarative UI Framework for Blender
author: Nicolai Prodromov

url: https://nicolaiprodromov.github.io
baseurl: /puree

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/nicolaiprodromov/puree" }

header_pages:
  - index.md
  - DOCS.md
  - SUPPORT.md
  - CONTRIBUTING.md

show_excerpts: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-seo-tag