title: Puree Documentation
description: Declarative UI Framework for Blender
theme: jekyll-theme-cayman

header_pages:
  - DOCS.md
  - CONTRIBUTING.md
  - SUPPORT.md

github_username: nicolaiprodromov
repository: nicolaiprodromov/puree

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'