title: Puree
description: Declarative UI Framework for Blender
author: Nicolai Prodromov

url: https://nicolaiprodromov.github.io
baseurl: /puree

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

github:
  repository_url: https://github.com/nicolaiprodromov/puree

copyright: "Copyright &copy; 2025 Nicolai Prodromov"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'

plugins:
  - jekyll-feed
  - jekyll-seo-tag