title: Puree
description: Declarative UI Framework for Blender

url: https://nicolaiprodromov.github.io
baseurl: /puree

remote_theme: just-the-docs/just-the-docs

# Enable dark mode by default
color_scheme: dark

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "Puree on GitHub":
    - "https://github.com/nicolaiprodromov/puree"

# Footer
footer_content: "Copyright &copy; 2025 Nicolai Prodromov. Distributed under the MIT License."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Heading anchor links appear on hover
heading_anchors: true